### ISSUE TITLE
Refactor nats files in s-enda 

### ISSUE THREAD

**Issue by myggen** [metno/discovery-metadata-catalog-ingestor#106]
Copy yaml-files from bases/nats  into environment/dev, environment/staging, environment/production and remove them from bases/nats/kustomization and add them to environment kustomizations . This is to be able to change one environment without affecting the others

**Comment by mortenwh** [comment]
@myggen - is this done?

**Comment by myggen** [comment]
> @myggen - is this done?

No. I want to wait until mmsd-nats-jetstream is ready before I possibly destroy the cluster(s) - And maybe must wait days for the k8s guys for help.   Then Johannes will no longer has a cluster to work against while doing development
