### ISSUE TITLE
Find out how to improve Continuous Deployment (CD)

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#107]
Currently, there is not really any automatic deployment of DMCI.

We want the following:

* Every new commit to master is deployed on the develop environment
* Every new tagged version is deployed on the staging environment
* Only manually specified versions of dmci is deployed on the production environment

This needs to be set up for other repos as well...

**Comment by mortenwh** [comment]
@aheimsbakk - can you help?

**Comment by aheimsbakk** [comment]
Yes, I can help. Should we look at the CI this week?

**Comment by johtoblan** [comment]
We make other issues for implementing CI/CD changes on the respective repos
