### ISSUE TITLE
Enforce namespace (e.g., no.met) requirement

### ISSUE THREAD

**Issue by johtoblan** [metno/discovery-metadata-catalog-ingestor#127]

**Comment by charlienegri** [comment]
is this something about making sure that the namespace is not empty?  
like making https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/dmci/api/worker.py#L174 return False if namespace is empty?

**Comment by johtoblan** [comment]
Yes indeed, the only accepted/true branch in the if-else should be namespace, uuid is present.
