### ISSUE TITLE
Require MMD data access and storage fields

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#144]
Currently, Arome Arctic datasets are coming through dmci without any data access fields. We should make that and the storage field required.

**Comment by magnarem** [comment]
Some datasets use a THREDDS-url instead of lustre-filepath for the <mmd:storage_information> <mmd:file_location> - element.

**Comment by mortenwh** [comment]
Both file path and opendap url should be provided. This will be handled in py-mmd-tools through https://github.com/metno/py-mmd-tools/issues/232 but we also need to check it in DMCI.

**Comment by johtoblan** [comment]
Needs to be set in mmd_strict

**Comment by mortenwh** [comment]
Also, we should probably check that the file and the opendap url exists. Is this possible for the file storage, when it is on lustre?

**Comment by johtoblan** [comment]
This can not be required due to metadata should be able to reference files that are removed. See discussion on the MMD-repo. We will implement a warning to the data-producer in py-mmd-tools if these fields are missing

**Comment by mortenwh** [comment]
See https://github.com/metno/py-mmd-tools/issues/253
