### ISSUE TITLE
Environment spcific customizations for metadata_identifer and landingpages are not applied in the distributors

### ISSUE THREAD

**Issue by magnarem** [metno/discovery-metadata-catalog-ingestor#153]
The data_mod changes in validator()-function in the worker.py that adds the env_string and modify or add the landing pages, are not used in the distributor.

So the modified data that comes back from the worker.validate(data) on line 132 in app.py is not the data used by the distributor called via the _distributor_wrapper, since the worker/distributor will read from the file in the workdir stored on disk on line 125 in app.py in the _persist_file(data,full_path)-function.
So the environment specific customizations are not applied to the mmd archive or the csw.

Proposed solution. If the mmd was altered in the validate() function then we will need to rewrite the updated file to the workdir, for the distributors to use the modified data.

I will create a branch and MR with a proposed solution, and we can discuss further.

**Comment by magnarem** [comment]
The code in branch `fix-issue-153` resolves the problem: 
A local test ingesting into local dev-environment, gives me the right environment-spesific identifier:
```
csw_db=# select identifier from records;
                   identifier                    
-------------------------------------------------
 no.met.dev:64db6102-14ce-41e9-b93b-61dbb2cb8b4e
 ```
 given the identifier of the input xml has was  `no.met:64db6102-14ce-41e9-b93b-61dbb2cb8b4e`.
 
 But in the case we are rebuilding catalog from the archive, witch then already have an identifier ` no.met.dev:b5126aaa-75c2-4a69-9191-e54ae5ca65c6
` then the ingested xml will get: 
 ```
                      identifier                      
-----------------------------------------------------
 no.met.dev.dev:b5126aaa-75c2-4a69-9191-e54ae5ca65c6
```

So in the data altering in the validate() function we will need to only change the identifier if it is not already changed.

I.e if identifier already has no.met.<env_string> then we do not modify that element. We only modify the indentifier  if no.met.<env_string> is missing from the identifier and we are in dev or staging.

This logic should apply for the following xml elements:
- mmd:metadata_identifier
- mmd:related_dataset
- mmd:related_information, dataset landingpage resource

**Comment by charlienegri** [comment]
noted, this branch should be merged before the one that will fix issue 152,  
I will copy the logic above from here and implement it in that branch for the parent dataset too  
the landing page update should already be implemented in such a way that this issue should not be a problem there (aka, if there is already a "Dataset landing page" block, we replace the entire content we do not use env_string from the config here but catalog_url)

**Comment by magnarem** [comment]
Creating an MR
