### ISSUE TITLE
SolR username and password should be given in the configuration file

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#170]
Currently, the SolR username and password are read from environment variables in the function `dmci.config.Config._read_solr_env_vars`. This is contradictory to the convention of using a configuration file. 

TODO:

- [ ] use envsubst to set solr username and password in config.yaml (should be null as default)
- [ ] remove the function `dmci.config.Config._read_solr_env_vars`

**Comment by johtoblan** [comment]
This is done directly to main, but needs to be added to the tests for dmci/config.py

**Comment by magnarem** [comment]
There is also possible to mount the solr credentials as a file in the os, and read them from the file. (this file will be in yaml format I recon). instead of environment variables.

This can be changed in the deployment.yaml for dmci in tjenester/s-enda

**Comment by johtoblan** [comment]
Will be done similarily to the postgis operator in pycsw, see: https://gitlab.met.no/tjenester/s-enda/-/blob/dev/base/csw/pycsw.yaml
