### ISSUE TITLE
Require metadata id on the form uri:UUID

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#171]
Currently, we are not consistently requiring `uri:UUID` formatted metadata ids (e.g., in delete functions). This is confusing, and should be changed.

**Comment by magnarem** [comment]
Note that the message sent back to mmd_agent (and possible the mms?) when a mmd file fails with return code `400`, will say something like:

`__main__:2023-05-24 09:45:16,740:ERROR:400,<string>:256:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.met.no/schema/mmd}long_name': This elemen │
│ t is not expected. Expected is ( {http://www.met.no/schema/mmd}short_name ).                                                                                     │
│  UUID : 3c7edfcb-1250-4c78-af45-f86200b1b076`

So the data-producer will get back `UUID: <uuid>`, and this might be confusing if we want delete/update to only accept identifers on the form `<ns>:<uuid>`. So either we have to allow both identifiers with or without namespace,
or make sure a `400` return status message from dmci, will be something like.
`
Error: 400 [something failed reaon message text]
Identifier: <ns>:<uuid>
`
So if the data-producer then want to delete or update that mmd file, it is clear that the identifier they will need to provide to the dmci endpoint when deleting is on the form `<ns>: <uuid>`

**Comment by mortenwh** [comment]
A consequence is, e.g., the following:

```
$ curl -X POST https://dmci.s-enda-dev.k8s.met.no/v1/delete/no.met.staging:6d1804fb-3f0c-4cbf-ac80-150e24ca67bd
The following distributors failed: pycsw, solr

$ curl -X POST https://dmci.s-enda-dev.k8s.met.no/v1/delete/no.met:6d1804fb-3f0c-4cbf-ac80-150e24ca67bd
The following distributors failed: file, pycsw, solr

$ curl -X POST https://dmci.s-enda-dev.k8s.met.no/v1/delete/no.met.dev:6d1804fb-3f0c-4cbf-ac80-150e24ca67bd
The following distributors failed: file
```

Note that the environment is wrong in the two first examples but that the file distributor deletion succeeds (in both, if they are run independently).

**Comment by mortenwh** [comment]
> Note that the message sent back to mmd_agent (and possible the mms?) when a mmd file fails with return code `400`, will say something like:
> 
> `__main__:2023-05-24 09:45:16,740:ERROR:400,<string>:256:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.met.no/schema/mmd}long_name': This elemen │ │ t is not expected. Expected is ( {http://www.met.no/schema/mmd}short_name ). │ │ UUID : 3c7edfcb-1250-4c78-af45-f86200b1b076`
> 
> So the data-producer will get back `UUID: <uuid>`, and this might be confusing if we want delete/update to only accept identifers on the form `<ns>:<uuid>`. So either we have to allow both identifiers with or without namespace, or make sure a `400` return status message from dmci, will be something like. `Error: 400 [something failed reaon message text] Identifier: <ns>:<uuid>` So if the data-producer then want to delete or update that mmd file, it is clear that the identifier they will need to provide to the dmci endpoint when deleting is on the form `<ns>: <uuid>`

Actually, the UUID provided in the error message here is the rejected file uuid, which determines the name of the rejected file, i.e., <uui>.xml. This is updated now, so it provides the filename of the rejected file.
