### ISSUE TITLE
testDistSolR_Init_with_auth not working as intended

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#173]
The issue is kind of explained in the docstring of `testDistSolR_Init_with_auth` but it doesn't seem to work that way... Would be nice to figure out how this works.

I.e., why does this pass:

`python -m pytest -vv --cov=dmci --cov-report=term-missing`

But not this:

`python -m pytest -v -s tests/test_dist/test_solr_dist.py::testDistSolR_Init_with_auth`

??

**Comment by johtoblan** [comment]
Why is testDistSolR_Init_with_auth testing example_config.yaml?
