### ISSUE TITLE
Add parent/child check and update for the pycsw-distributor instead of depending on the parent-uuid-list.xml

### ISSUE THREAD

**Issue by magnarem** [metno/discovery-metadata-catalog-ingestor#200]
For pyscw we are now dependent on updating the parent-uuid-list.xml file for registering parent datasets. This can be avoided by adding some extra checks and updates to the pysw-distributor, similar done in the solr-distributor.

*Check incoming file for ```related_dataset relation="parent"```. Check if there is a record in the pycsw catalog with that identifier.
* If not, provide error message that says that the parent have to be indexed first.
* If the parent record exist, check that the parent have ```hierarchyLevel='series'```. If set, OK. if not set. update record.

Then we will not require the parent-uuid-list.xml file anymore.

**Comment by mortenwh** [comment]
@Teddy-1000 - mulig denne kunne vært fin for deg også!

**Comment by johtoblan** [comment]
Should be done in worker.
Need to change the XSLT-transform schema, since it now relies on parent_list

**Comment by mortenwh** [comment]
As far as I understand from @Teddy-1000 this was not as straight forward as first thought. We are working on a solution in ADC related projects that may work instead, so moving this into the ice box.

**Comment by mortenwh** [comment]
to be solved in ADC
