### ISSUE TITLE
Add WMS links to Arome Arctic datasets

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#209]
@TAlonglong has prepared mapscript to handle arome arctic netcdf datasets.

TODO: update the AA deterministic MMD files with wms-links.

En kan spørre slik: https://fastapi.s-enda-dev.k8s.met.no/api/get_quicklook/arome_arctic_det_vdiv_2_5km_20231020T09Z.nc

Du får da getcapabilities dokumentet.
Et eksempel på wind_speed data: https://fastapi.s-enda-dev.k8s.met.no/api/get_quicklook/arome_arctic_det_vdiv_2_5km_20231020T09Z.nc?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=wind_speed&WIDTH=1220&HEIGHT=860&CRS=EPSG%3A3857&BBOX=-1240804.7299879682,9141056.7566646,4097429.478409829,12904074.313404031&STYLES=&FORMAT=image/png&TRANSPARENT=TRUE&&TIME=2023-10-23T03%3A00%3A00Z

Eller air_temperature_pl i 400hPa: https://fastapi.s-enda-dev.k8s.met.no/api/get_quicklook/arome_arctic_det_vdiv_2_5km_20231020T09Z.nc?&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=air_temperature_pl&WIDTH=1220&HEIGHT=860&CRS=EPSG%3A3857&BBOX=-4398348.3862462165,8491826.838081796,7612678.58264883,16958616.340745516&STYLES=&FORMAT=image/png&TRANSPARENT=TRUE&&TIME=2023-10-20T18%3A00%3A00Z&DIM_PRESSURE=400.0

Modulen som brukes er ganske generell. Jeg skal utifra denne modulen prøve å lage en generell modul som ikke er netcdf fil spesifik.

**Comment by TAlonglong** [comment]
https://gitlab.met.no/mmd/mmd-xml-dev/-/merge_requests/21 review this first. ANd the I will make staging and production when I know when this dev is ok

**Comment by TAlonglong** [comment]
Her ser det bra ut. Dette datasettet i dev for eksempel  https://data-test.met.no/dataset/ae1aaba6-f108-4558-af29-30593ed49be1 har wms link som svarer med getcapabilities. Og viser riktige resulktater i for ekesemple geoweb

Det samme gjelder staging og prod, men det mangler promote fra dev til staging og prod. Så jeg tror dett er ok
