### ISSUE TITLE
Add autentication to DMCI

### ISSUE THREAD

**Issue by aheimsbakk** [metno/discovery-metadata-catalog-ingestor#223]
Add simple API key or JWT autentication to DMCI with an NGINX proxy.

Example of API key auth:  https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-1/

**Comment by mortenwh** [comment]
@shamlymajeed - can this be prioritized?

**Comment by mortenwh** [comment]
Closing this, as it is handled by the dmci-proxy which is a separate repo
