### ISSUE TITLE
Implement rejected-folder.

### ISSUE THREAD

**Issue by johtoblan** [metno/discovery-metadata-catalog-ingestor#46]
If a job is validated, but not distributed properly, the user is not informed. To allow this we must implement a rejected-folder to identify failed jobs.

**Comment by johtoblan** [comment]
Will be discussed at sprint tomorrow

**Comment by mortenwh** [comment]
Is this relevant anymore? @vkbo

**Comment by vkbo** [comment]
Yes, absolutely.

**Comment by johtoblan** [comment]
- [ ]  Implement rejected folder (Needs to be permanent on kubernetes side?) 
- [ ]  Move rejected to rejected folder
- [ ]  Delete non-rejected
