### ISSUE TITLE
Reimplement vocabulary checks in full_check 

### ISSUE THREAD

**Issue by johtoblan** [metno/discovery-metadata-catalog-ingestor#49]
Full_check is being disabled due to 401 on our get requests through pythesint. This should be rewritten after the sprint to actually check files.

**Comment by vkbo** [comment]
Checking of URLs part is split out into issue #68

**Comment by johtoblan** [comment]
vocab.met.no to replace pythesint?

**Comment by mortenwh** [comment]
The rest of this job will be done in metno/py-mmd-tools#106

**Comment by mortenwh** [comment]
Mark as dependent instead...
