### ISSUE TITLE
Make solr ingestor

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#80]
A solr ingestor is needed in order to use the dmci approach in nbs and other related projects.

**Comment by mortenwh** [comment]
@vkbo - could Fabio work on this? When would we be able to do it?

**Comment by fzeiser** [comment]
I *might* be able to do this, but I'm not sure that this is realistic before I resign at MET (end of August).

**Comment by mortenwh** [comment]
Avventer avgjørelse på ny arkitektur.

**Comment by johtoblan** [comment]
Depends somewhat on https://github.com/geopython/pycsw/issues/208. Prioritize PYCSW ingestor and agent over this

**Comment by mortenwh** [comment]
@magnarem @steingod - can you help us with this?

**Comment by magnarem** [comment]
> @magnarem @steingod - can you help us with this?

I can help with this.
