### ISSUE TITLE
DMCI insert should be changed to create

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#88]
I.e., `curl --data-binary "@<PATH_TO_MMD_FILE>" localhost:5000/v1/insert` should be `curl --data-binary "@<PATH_TO_MMD_FILE>" localhost:5000/v1/create`

NOTE: v0.3 can have both `insert` and `create` but only `create` must be in v1.0 onwards.

**Comment by johtoblan** [comment]
Added alias for insert: create.
